---
exclude: ['README.markdown']
permalink: ':title'
highlighter: pygments
safe: false
title: 'Open Council Data Standards'
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]